# CI/CD pipeline con Build, Secret Detection e SAST

stages:
  - build
  - test
  - sast
  - secret-detection

variables:
  SECRET_DETECTION_ENABLED: 'true'
  SAST_EXCLUDED_ANALYZERS: 'brakeman'  # <-- opzionale, dipende dalla tecnologia del tuo progetto

# JOB: Build del progetto con Gradle
build_project:
  stage: build
  image: eclipse-temurin:21-jdk
  before_script:
    - apt-get update && apt-get install -y git
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - chmod +x ./gradlew
  script:
    - ./gradlew build
  only:
    - merge_requests
    - main
    - master

# Inclusione dei template di sicurezza GitLab
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# Override dei job per impostare la scadenza degli artifacts
sast:
  artifacts:
    expire_in: 7 days

secret_detection:
  artifacts:
    expire_in: 7 days  