name: Build and Push to GitLab

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Push branch to GitLab
      if: success() && (github.event_name == 'push' || github.event_name == 'pull_request')
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/BlackWyrm14/forghitel.git"
        BRANCH=${{ github.head_ref || github.ref_name }}
    
        # Recupera gli ultimi aggiornamenti da GitLab
        git fetch gitlab $BRANCH
    
        # Integra eventuali modifiche (merge automatico)
        git merge --strategy=recursive --strategy-option=theirs gitlab/$BRANCH || true
    
        # Ora puoi pushare
        git push gitlab HEAD:refs/heads/$BRANCH

